spring.application.name=payment-service
server.port=8080

logging.structured.format.console=logstash
management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true

management.tracing.sampling.probability=1.0
